language: java
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "notification-system"
    token:
      secure: $SONAR_TOKEN

script:
  # - ./scripts/verify_code_format.sh
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

services:
  - docker

after_success:

  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG

