language: java
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "notification-system"
    token:
      secure: qZNFCjF5uZYJvTjRdfmBjWJ5ub7ZA/WrKoMxi9BSVpBllimf1j4eLLGJe3i7u5fsJpglkKzwXLMIHWNBcPXa7SJzHX4SpTlDStreHhzjlIniNZziog4EwVOkSYCsCeqqJ48xEi2rHuocSDM9B/09EYfX4uxsCe9vwT67Z2To5be2TzPEBkgspuxzR7fwn77EvMpAPkXuCGQG+dymHn/re6Qp1nNPRCU2GEjuOKsUsro9pZLElyNISOqVq2Ig9xd2J3xV8BDoSBPuOZjRGgYahv6SRiapeItMweEX5T4Hz4qu6d6x5N2WwwwQjP/bvx9ksglnvCqOaM6UMz+oxSrsjCFBzCPqNc8zEpJ31cr4iLWbWo1t5/wPr91YxiV5e/VkXsFOOvHuJ2hbZD7m0Wx/WavnGsA5bof356H7c8ciz7uuv2LDq7InEMaHuzXE69s71wSqfUxrW8/yvHdCipTPGsBZyZUwm7+ooSbI3QB4OJyis6Eu6W4Yz6NDp+eXHOxnGkZfFN17mSKQgvRrhsPD2YuDhEqUMCLT2U09QDJEEtZ/dX0GJevJH+Gydqz4A8FeGqOSdRL4sUXXcXvoORNcXHTOjx2adCl9jWpDp+AgYOsjXjry8XPBRhCbAnFvjsvxnGhR+vQBKzHavUXlQKQIIVzpMZ1rYhvDgQk5SwyETPc=

script:
  # - ./scripts/verify_code_format.sh
  #- ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

services:
  - docker

after_success:
- if tag IS present; then
   docker login -u $DOCKER_USER -p $DOCKER_PASS
   docker build -t $IMAGE_TAG .
   docker push $IMAGE_TAG
  fi
