language: java
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "notification-system"
    token:
      secure: kAOVrV/uAN06lmIwG9I4Fmhro5bmWAGYGVdII5cHBRRVsq2NXTNL0oPtBXDbjUeJd37/RsnvHdr/FCfNZym69HPvMzfVNKfbkY8GGoF4OjrhgV3fx835yl6r8WfYm7Zk27TiSk7Q9XE58eCZosDhBKdK+kWvAAs3pFTvz2ksTkk0K5zSJL03/dDgyhHP/98rOasPKe6895fxrf+5m/ThFhosjNgfbLfvS+c+oR3j6pjPmAhNigiejCaYXaioh++RG+KPrd4zTxSROHU9XR/Y4Eoblju+3C2wYzEIfrWNuEbOfdGhSZzxbfyFrDpLQm0fp0OnweU+plHXwZpR1DZqoRi75R0aKeTdXwVohcxrwGk8+jhBGIlBwHStjUio5HZqlsz7BWHHTJ7dGU0jLKHHQH3JlzAn9WtrtAW4NV0l5fpAzPZ6/ranFBDC7ft4HHf9VmAIz4ddUg5GKPZuI3fMse62pxEhpxareBgUG+Pn86kPxh79joNmUIY0vnuXlhOoU91UX+zMXXjWVkcrrBgRUiq5oq0SYP97tsvKtgqZ/aTnKjxG1zGTNhqYxVprCwJTUxhm3Vho0G4gACuF6qlX7zF9x0kW5TohpAxfkQSF27jNky8B0k9pqnJ3/RamyircNDW3jkFtq3Hzutf4D3YtCRT5W6xaG3khTC4e/d9UeGM=

script:
  # - ./scripts/verify_code_format.sh
  #- ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

services:
  - docker

after_success:
- if tag IS present; then
   docker login -u $DOCKER_USER -p $DOCKER_PASS
   docker build -t $IMAGE_TAG .
   docker push $IMAGE_TAG
  fi
